services:
  splent-api:
    build: .
    container_name: splent-api
    restart: always
    ports:
      - "${SPLENT_API_HOST_PORT:-5000}:80"
    env_file:
      - .env
    environment:
      PACKAGES_FILE: /data/packages.json
    volumes:
      - ./data:/data
